[env]
YT_DLPP_MISE_ACTIVE = 'true'
V0_API_KEY = ''

[settings]
env_file = '.env'

[tools]
ruff = { version = '0.16.8' }
uv = { version = '0.12.18' }
ty = { version = '0.0.84' }
python = { version = "3.14.7" }

[tasks]
claude = 'npx --yes @anthropic-ai/claude-code@latest'
